### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by ebourg** [codehaus-plexus/plexus-sec-dispatcher#3]
The repository is missing the release tags, here are the commands to add them:

    git tag 1.4   7db8f880486e192a1c5ea9544e01e756c3d49d0f
    git tag 1.3.1 36cf1710ec7138d00c9615f22e32cd5a837171f4
    git tag 1.3   9b79e65fb08ffae34d6074a3a1dde14440a2652a
    git tag 1.2   86a006598e752c579a6d2551c17884f15eb0f992
    git tag 1.1   cbe09e7492bb4dbae1d1e4642525b666be17e9fd
    git tag 1.0   00c60a55a1ce449304d62b1b2ae5c7530d28a126
    git tag 1.0-alpha-3 00edf6ae929fe45507d088c9db57bedf926835ff
    git tag 1.0-alpha-2 13e6a32d0b1c6821d5bead10c081da7bb9504f77
    git tag 1.0-alpha-1 84d3a14a6320eef2c0adc070bc777fbaf1d3ef81
    git push --tags

**Comment by slachiewicz** [comment]
fixed
