### ISSUE TITLE
Missing documentation site

### ISSUE THREAD

**Issue by slawekjaranowski** [codehaus-plexus/plexus-sec-dispatcher#36]
Documentation site is missing ... but someone try to visit it  form time to time

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/3578921/185571957-650bb262-d196-4a56-95b2-f3ce9834a273.png">

**Comment by cstamas** [comment]
Published site, but it sees gh-pages are not set up? On push to gh-pages branch the "publish" action does not run

**Comment by cstamas** [comment]
Also, pls update the project home page with site link

**Comment by slachiewicz** [comment]
fixed.
